version: "3"

services:
  postgres:
    image: postgres:10
    container_name: postgres-db
    tty: true
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=establishment-db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    networks:
      - node-network
  api:
    build:
      context: .
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 40s node server.prod.js
    tty: true
    container_name: api
    environment:
      - DB_HOST=postgres
    ports:
      - 4000:4000
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
